#!/usr/bin/env bash
# Configure redirection
echo "
server {
    listen 80;
    server_name localhost;

    location / {
            root /var/www/html;
                    index index.html;
        }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

}
" | sudo tee /etc/nginx/sites-available/redirect_me

sudo rm /etc/nginx/sites-enabled/default 2>/dev/null
sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/
sudo nginx -t && sudo /etc/init.d/nginx restart